### ISSUE TITLE
[Model Zoo] TODO list of implementing model zoo

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#1063]
Design doc: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/model_zoo.md

1. [ ] unify SQLFlow and ElasticDL custom models https://github.com/sql-machine-learning/models/issues/22.
1. [x] support keras functional API models: https://github.com/sql-machine-learning/sqlflow/issues/1093
1. [x] support parse model name like `a_data_scientist/regressors:v0.2/MyDNNRegressor`
1. [ ] support pytorch custom model in model zoo.
1. [x] base Docker image for building all model Docker images, with python, ElasticDL, and other common dependencies.
1. [x] save model weights in a database table with columns of metadatas. (save in MySQL, Hive, MaxCompute)
1. [ ] HTTP service `models.sqlflow.org` to serve publishing and listing models.
1. [ ] submitter program runs a model in a docker image.
1. [ ] support using `models.sqlflow.org` in SQL statements.
1. [ ] support `SQLFLOW LIST|PUBLISH` command.

**Comment by typhoonzero** [comment]
Related with couler: https://github.com/sql-machine-learning/sqlflow/issues/1066

**Comment by typhoonzero** [comment]
Model zoo is implemented in latest SQLFlow.
