### ISSUE TITLE
TODO:Argo workflow on SQLFlow

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#1066]
- gRPC interface
    -  Server
        - [x] Update server `sqlflowserver.proto` to add `Run` and `Fetch` interface #1198 
        - [x] gRPC `Fetch` interface invoke argo.Fetch to fetch logs and status. #1525 
     - [x] pysqlflow
        - [x] Implement `Run` and `Fetch`.
- Couler
    - [x] Design: Couler step function: https://github.com/sql-machine-learning/sqlflow/pull/1208
    - [x] sqlflowserver calls `codegen_couler.go` to generate Couler program. #1268 
- Argo
    - submit Argo workflow
         - [x] `kubectl` command-line to submite the Argo YAML. #1252 
         - [x] Add e2e test for Couler and Argo. #1245 
         - [x]  `codegen_couler.go` generates Argo yaml with speicify cluster configuration file. #1379
    - [x] fetch worfklow status #1375 
    - fetch workflow steps logs
        - [x] fetch one step logs
        - [x] fetch multiple steps logs #1367 
        - [x] fetch logs in a incremental way #1382 
        - [x] fetch running workflow #1459
- [x] Argo
    - [x] Doc: Submit Argo workflow: https://github.com/sql-machine-learning/sqlflow/pull/1079
    - [x] Setup Argo testing environment in CI: #1219
- [x] Parser
    - [x] `sqlflowserver` calls third-party Parser to parse/split the SQL program.
- [x] SQLFlow command line
    - [x] `sqlflow -parse` to generate IR as a Protocol Buffer text file

**Comment by tonyyang-svail** [comment]
I am closing this issue since we have completed all the items. Great job! @Yancey1989
