### ISSUE TITLE
[train&val] Support VALIDATE while running TRAIN

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#1111]
According to #675, we are going to support the user specify dataset for validation by adding a  `VALIDATE ON` in `TRAIN` statement:
```SQL
SELECT ... 
TO TRAIN DNNClassifier
...
INTO my_model
VALIDATE ON (SELECT ...)    -- validation dataset
```

At this moment,  we plan to implement a workaround solution first due to the technical schedule.
```SQL
SELECT ... 
TO TRAIN DNNClassifier
WITH
    validation.dataset="SELECT ...",         -- validation dataset
    validation.loss_fun="loss_function"
...
INTO my_model;
```

- ~~Add keyword `VALIDATE ON` in `sql.y`.~~ PR: #1112  
- [x] Support specify `VALIDATE` dataset in `WITH` clause. #1124
- [x] Switch the old approach `train&val` to the `VALIDATE` mode #1124
- [x] Bring back validation for XGBoost #1130 
- [x] Verify the schema of `validation dataset` specified by `VALIDATE ON`

**Comment by tonyyang-svail** [comment]
Hi @weiguoz, thanks for submitting this TODO list.

We need to make several design choices before rushing into implementation
1. Since we will be changing `TRAIN` to `TO TRAIN`, do we need to change `VALIDATE` to `TO VALIDATE`? Why?
1. Are parentheses `(` `)` required for specifying the validation select? Why?
1. Are we supporting arbitrary select statements? Why?
1. Should `VALIDATE` support the `WITH` clause in case we need to specify some configurations?

**Comment by weiguoz** [comment]
Thanks for reminding me. 
I'm aware that this direct solution may have some technical risks. Considering this feature(supporting `validate`) has a higher priority. I would propose to specify the validation dataset in the `WITH` clause.

When more user suggestions are collected, we will back here adding the keyword `VALIDATE `.

**Comment by weiguoz** [comment]
> Hi @weiguoz, thanks for submitting this TODO list.
> 
> We need to make several design choices before rushing into implementation
> 
> 1. Since we will be changing `TRAIN` to `TO TRAIN`, do we need to change `VALIDATE` to `TO VALIDATE`? Why?
> 2. Are parentheses `(` `)` required for specifying the validation select? Why?
> 3. Are we supporting arbitrary select statements? Why?
> 4. Should `VALIDATE` support the `WITH` clause in case we need to specify some configurations?

Thanks for reminding me. 
I'm aware that this direct solution may have some technical risks. Considering this feature(supporting `validate`) has a higher priority. I would propose to specify the validation dataset in the `WITH` clause.

When more user suggestions are collected, we will back here adding the keyword `VALIDATE `.

**Comment by weiguoz** [comment]
@Echo9573 SQLFlow has supported specifying the dataset for validation in `WITH` clause

1. TensorFlow
```SQL
SELECT *
FROM iris.train
TO TRAIN DNNClassifier
WITH
    model.n_classes = 3,
    model.hidden_units = [10, 20],
    validation.select = "SELECT * FROM iris.train limit 20" -- a SELECT statement
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class
INTO sqlflow_models.my_dnn_model
```

2. XGBoost #1130 
``` SQL
SELECT *
FROM iris.train
TO TRAIN xgboost.gbtree
WITH
  objective="multi:softprob",
  train.num_boost_round = 30,
  eta = 0.9,
  num_class = 3,
  validation.select = "SELECT * FROM iris.train LIMIT 20" -- please change iris.train  to your table
COLUMN sepal_length, sepal_width, petal_length, petal_width
LABEL class 
INTO sqlflow_models.my_xgboost_model;
```

**Comment by Echo9573** [comment]
Thanks for your contribution! I will test this later.
