### ISSUE TITLE
SQLFlow Parser TODO list

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1126]
Design Doc: https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/sqlflow_parser.md

Step 1: support arbitrary select statement

- [x] Change `TRAIN/PREDICT/ANALYZE` to `TO TRAIN/TO PREDICT/TO EXPLAIN`.
- [x] Connect third party parser.
    - [x] Connect Parser in Go.
    - [x] Connect Parser in Java.
- [x] ~~Update `sql.y` to remove `standardSelect` field.~~
    - [x] ~~Port ALPS to IR.~~
    - [x] ~~Port EDL to IR.~~

Step 2: support SQL program

- [x] Split SQL program in `package sql` instead of `package server`.
- [x] Update IR to support SQL programs.

**Comment by tonyyang-svail** [comment]
I am unable to remove the `standardSelect` field in `sql.y` because the codegen ALPS and EDL are depending on it.
