### ISSUE TITLE
TODO: Katib on SQLFlow Implementation

### ISSUE THREAD

**Issue by samplise** [sql-machine-learning/sqlflow#1544]
- [ ] SQLFlow parser:
  - [ ] Parse SQL statement and generate `IR` for Katib training job.
- [ ] Katib codegen:
  - [ ] Add Katib codegen codes in `couler_codegen.go`.
  - [ ] Implement `katib.go`.
- [ ] Implement `couler.sqlflow.katib.train` API in Couler.
- [ ] Implement `xgb_train.py`.
  - [ ] Put parameters' value in the environment.
- [ ] Implement `katib_xgboost_submitter.py` (or update existing `xgboost_submiiter.py`): 
  - [ ] Make the output format be compatible with Katib requirements.
- [ ] Log collection for Katib:
  - [ ] Identify the major Pods in a Katib job and collect logs from them.

**Comment by gaocegege** [comment]
Hi

I am one of the katib maintainers. Glad to see the awesome feature! Could you please add the information about the adoption in https://github.com/kubeflow/katib/blob/master/docs/community/adopters.md? We are working on a post and may have a section to illustrate the adoption of katib in industries. We are glad to introduce sqlflow in the post as a case study.

Thanks.
