### ISSUE TITLE
Run XGBoost Train/Explain with AlisaSubmitter on Dataworks

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#1819]
From the current implementation of [xgboost/train.py](https://github.com/sql-machine-learning/sqlflow/blob/develop/python/sqlflow_submitter/xgboost/train.py), 
https://github.com/sql-machine-learning/sqlflow/blob/320ce7222f82de00594cb5eb31644cec1bb7b2df/python/sqlflow_submitter/xgboost/train.py#L22-L23

XGBoost reads data from MaxCompute with AK/SK, but on Dataworks with PAI, we can not using AK/SK instead of the API `tf.data.TableRecordDataset`:
https://github.com/sql-machine-learning/sqlflow/blob/320ce7222f82de00594cb5eb31644cec1bb7b2df/python/sqlflow_submitter/tensorflow/input_fn.py#L135-L139

We need to update the XGBoost codegen to use `tf.data.TableRecordDataset` to read data from Maxcompute, so we can `Train/Predict/Explain` XGBoost model on Dataworks.

## TODO
- [x] Run XGBoost on Dataworks. @Yancey1989  #1827 
- [x] Run SHAP on Dataworks. @weiguoz #1848 
- [ ] Enable workflow Fetch interface returns HTML content of Pod logs which run SHAP task. @Yancey1989

**Comment by typhoonzero** [comment]
Can use `TableRecordDataset` to generate the xgboost training files

**Comment by tonyyang-svail** [comment]
I believe "XGBoost Train/Explain with AlisaSubmitter on Dataworks" has been supported.
