### ISSUE TITLE
Output detailed error message of the failed workflow step on SQLFlow client

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#2119]
The related design:  #2110 

TODO tasks:
- [x] goalisa `ExecCode(code string)` -> `ExecCode(code string, w io.Writer)` to write logs into `io.Writer` https://github.com/sql-machine-learning/goalisa/issues/36
- [x] pick PAI task URL and error message from Alisa logs. #2151 
- [x] output error message if the workflow step failed. #2135
