### ISSUE TITLE
Model zoo TODO list

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#2307]
We are implementing the model zoo currently. Here is the [overall design](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/model_zoo.md) and [how users contribute custom models under this design](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/contribute_models_new.md)

- [x] Model zoo server @typhoonzero 
    - [x] GRPC server which handle user model releasing and deleting operations.
    - [x] upload model directory and get class names/function names of the models.
    - [x] build and push a Docker image when releasing a model collection.
    - [x] release trained models saved in DBMS
    - [ ] release trained models saved in OSS
- [x] Command line tool @lhw362950217 
    - [x] release model definitions
    - [x] release trained models
    - [x] delete shared model definitions or trained models

**Comment by Yancey0623** [comment]
>  release trained models saved in DBMS
 release trained models saved in OSS

If we can save the trained model by SQLFS with OSS and DBMS backend, that we only need to release the trained model from SQLFS. The above two TODO tasks can be

- [ ] SQLFS supports OSS as the backend.
- [ ] release trained models saved in SQLFS.

BTW. If we use OSS as the backend, that is not the SQL engine, maybe we should rename `SQLFS` to a more meaningful name?
