### ISSUE TITLE
[TODO LIST] XGBoost feature column support

### ISSUE THREAD

**Issue by sneaxiy** [sql-machine-learning/sqlflow#2347]
Related to https://github.com/sql-machine-learning/sqlflow/pull/2345 .

- [x] TensorFlow-like feature column transformer in Python
- [x] Data transformation before dumping to DMatrix in Python db generator
- [x] Golang `deriveFeatureColumnCode` code for XGBoost
- [x] Feature column support for train/predict/evaluate/explain codegen template of XGBoost
- [x] Save PMML file during training

**Comment by sneaxiy** [comment]
Fixed by https://github.com/sql-machine-learning/sqlflow/pull/2361, https://github.com/sql-machine-learning/sqlflow/pull/2416 and https://github.com/sql-machine-learning/sqlflow/pull/2411 .
