### ISSUE TITLE
TODO list of deploy model zoo server on-premise

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/sqlflow#2474]
- [x] save the model on Maxcompute using `sqlfs` package so that the SQLflow cli can download the model and do release.
- [x] the deployed server should support `docker build` or:
- [ ] support build Docker images using [kaniko](https://github.com/GoogleContainerTools/kaniko)
- [ ] support release model stored on OSS (https://github.com/sql-machine-learning/sqlflow/issues/2307)
- [x] save model metas when training and release models with more information(https://github.com/sql-machine-learning/sqlflow/pull/2456)
- [ ] do the deployment
