### ISSUE TITLE
Roadmap of the refactory

### ISSUE THREAD

**Issue by shendiaomo** [sql-machine-learning/sqlflow#2591]
I propose to split the refactory development into three stages to ensure a smooth transition. The output of each stage is more easily guaranteed to be correct.

## Stage 1: Decouple codegen and execution. 
- [ ] Add an interface in sqlflow.runtime for normal queries #2587 
- [ ] Process figures generated by explanation statements in sqlflow.runtime #2588 
- [ ] Implement pyalisa and model saver/loader in Python #2565
- [ ] Supports submitting pai/alisa tasks in sqlflow.runtime #2590 
- [ ] Modify the `Executor` structs to be `CodeGenerators` #2562 

## Stage 2: Feature Derivation
- [ ] Implement feature derivation and verifier in Python #2568

## Stage 3: The compiler
- [ ] Supporting generating code for an executable #2562 
- [ ] Build a SQLFlow compiler command-line tool #2529
