### ISSUE TITLE
First milestone of code generator refactor with XGBoost

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#2667]
As the updated design of code generator #2640 , the first milestone of the refactoring should be simple and convert most APIs implementation, that we can iterate quickly on the other AI engine and AI platform APIs, a good choice is XGBoost train/predict/explain, the TODOs is as the following:

- `runtime` APIs with XGBoost
    - [x] `runtime.local.xgboost.train `
    - [ ] `runtime.local.predict `
    - [ ] `runtime.local.explain `
    - [x] `runtime.model.save ` #2711 
    - [x] `runtime.model.load `. #2711 
    - [x] `runtime.feature.derivation`.  #2735, #2739
    - [ ] `runtime.verifier `. #2706, #2708
    - [ ] `runtime.db.query`
    - [ ] `runtime.db.exec`
- [ ] add `CodeGenerator` Go interface as design doc allude to.
- [ ] code generator to generate submitter program runs on local host.
- [ ] workflow call the default codegen.

**Comment by lhw362950217** [comment]
runtime.db.exec has been implemented by https://github.com/sql-machine-learning/sqlflow/pull/2661

**Comment by lhw362950217** [comment]
Shall we put all train code to runtime.local.train package like predict and explain?

**Comment by typhoonzero** [comment]
Done at `python/runtime/local`, closing.
