### ISSUE TITLE
Move MySQL and Hive CI to use the refactorized codegen

### ISSUE THREAD

**Issue by sneaxiy** [sql-machine-learning/sqlflow#2985]
The PR https://github.com/sql-machine-learning/sqlflow/pull/2970 tries to move all MySQL and Hive CI tests to the refactorized codegen. But there are still several issues to be resolved before the CI movement. 

The issues are listed as follows:
- [x] Model zoo supports the saved models: https://github.com/sql-machine-learning/sqlflow/issues/2978 - @typhoonzero PR: https://github.com/sql-machine-learning/sqlflow/pull/2992
- [x] TestConvergenceAndAccuracy fails on MySQL: https://github.com/sql-machine-learning/sqlflow/issues/2979 - @sneaxiy PR:  https://github.com/sql-machine-learning/sqlflow/pull/2988
- [x] CaseTestOptimizeClauseWithoutGroupBy fails on MySQL: https://github.com/sql-machine-learning/sqlflow/issues/2980 - @sneaxiy PR: https://github.com/sql-machine-learning/sqlflow/pull/2986
- [x] Incorrect integer value error on MySQL: https://github.com/sql-machine-learning/sqlflow/issues/2981 - @sneaxiy  PR: https://github.com/sql-machine-learning/sqlflow/pull/2987
- [x] ValueError: unrecognized dtype 1 on MySQL: https://github.com/sql-machine-learning/sqlflow/issues/2982 - @sneaxiy PR: https://github.com/sql-machine-learning/sqlflow/pull/2989
- [x] caseShowTrain fails on Hive: https://github.com/sql-machine-learning/sqlflow/issues/2983 - @sneaxiy PR: https://github.com/sql-machine-learning/sqlflow/pull/2993
- [x] step_entry_0 not found on Hive: https://github.com/sql-machine-learning/sqlflow/issues/2984 - @sneaxiy PR: https://github.com/sql-machine-learning/sqlflow/pull/2993
- [x] the Python feature derivation is a bit different from the Go feature derivation. Should fix the bugs caused by the differences - @sneaxiy PR: https://github.com/sql-machine-learning/sqlflow/pull/2999
- [x] support incremental training. - @sneaxiy PR: https://github.com/sql-machine-learning/sqlflow/pull/3000

**Before you run these test cases, please `export SQLFLOW_USE_EXPERIMENTAL_CODEGEN=true` to use the refactorized codegen.**
