### ISSUE TITLE
[Feature Request] Implement SQLFlow Session

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#531]
**Is your feature request related to a problem? Please describe.**

For the current SQLFlow architecture,  we should deploy SQLFlow with 1-1 mapping from Notebook server instance and the SQLFlow gRPC server instance, it's unprofitable to the scalability and optimizes the resource utilization. The new feature `SQLFlow Session` can deploy the two components with the 1-N mapping.
 
Some discussion: #399 

### Tasks:

- [x] [Done] Design doc. #501 
- [x] [Done] add e2e test to ensure the all-in-one Docker image availability. #529 
- [ ] ~[Discussion]  How to maintain the proto file in the seperate repos(sqlflow/pysqlflow) https://github.com/sql-machine-learning/pysqlflow/issues/69~
- [x] [Done] implement session in the server side (sqlflow) #530 
- [x] [Done] implement session in the client side (pysqlflow) https://github.com/sql-machine-learning/pysqlflow/pull/71
- [x] [Done] A tutorial to deploy SQLFlow cluster on k8s. #537

**Comment by tonyyang-svail** [comment]
I am closing this issue since having two proto definitions is working okay.
