### ISSUE TITLE
SQLFlow Predict SQL generate ODPS UDF program

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#604]
**Is your feature request related to a problem? Please describe.**

SQLFlow would use ODPS UDF as the Alps prediction Job, for a simple example prediction UDF program:

``` text
set mst.model.name=push_common.model;
set mst.oss.id=aaa;
set mst.oss.key=bbb;

.....

SELECT sqlflow_projet.alps_inference(
            concat_ws(",",user_id,label)
            ,1
            ,"deep_id"
            ,COALESCE(deep_id, "")
        ) as (user_info, score)
FROM sqlflow_projet.users;
```

The SQLFlow Predict SQL can be like:

```  SQL
SELECT sqlflow_projet.alps_inference(
            concat_ws(',',user_id,label)
            ,1
            ,"deep_id"
            ,COALESCE(deep_id, "")
        ) AS (user_info, score)
FROM sqlflow_projet.users
PREDICT sqlflow_project.pred_result
USING sqlflow_model;
```

There would be two tasks to finish this feature:
- [x] SELECT fields syntax need to support ODPS UDF syntax. #600 
- [x] codegen_alsp can generate the ODPS UDF program and execute through the ODPS database interface. #604 
- [ ] [gomaxcompute](https://github.com/sql-machine-learning/gomaxcompute) need to support adding the query  settings. https://github.com/sql-machine-learning/gomaxcompute/issues/45

NOTE: For the future, we need a more general solution to parse the standard SQL syntax.

**Comment by tonyyang-svail** [comment]
This issue has been fixed.
