### ISSUE TITLE
Train and val

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#624]
Following the design: [training_and_validation](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/training_and_validation.md)

SQLFlow supports train&val on [Maxcompute](https://www.alibabacloud.com/product/maxcompute) for `alps` through 4 PRs:
- [x] [generate a temporary](https://github.com/sql-machine-learning/sqlflow/issues/568)
- [x] [split temporary table](https://github.com/sql-machine-learning/sqlflow/issues/569) 
- [x] [codegen for alps](https://github.com/sql-machine-learning/sqlflow/issues/570)
- [x] [release temporary table](https://github.com/sql-machine-learning/sqlflow/issues/571)

Next, we are going to implement:
- [x] [support train&val on Maxcompute for TF](https://github.com/sql-machine-learning/sqlflow/pull/638)
- [x] [support train&val on Hive](https://github.com/sql-machine-learning/sqlflow/issues/644)
- [x] [support train&val on MySQL](https://github.com/sql-machine-learning/sqlflow/issues/684)
