### ISSUE TITLE
[TODO List] Ant-XGBoost on sqlflow 

### ISSUE THREAD

**Issue by sperlingxx** [sql-machine-learning/sqlflow#630]
This is TODO list for milestone 1; running Ant-XGBoost locally on SQLFlow server.

## SQLFlow
- [x] design doc #579 
- [x] [Dockerfile] Install ant-xgboost in SQLFlow Docker image . #647 
- [x] [python] SqlflowDataSource #647 
- [x] xgboost template  #662 
- [x] A SQLFlow tutorial to run in notebook #772
- [x] user guide #772
- [x] SQLFlow magic supports to switch submitter in notebook, need to add SQLFLow_submitter field in the Session struct.  #662 
- [x] [golang] XGBoostFiller refine.  #651 
- [x] Integrate model performance verification in CI.  #767 

## ant-xgboost
* xgblauncher
   - [x] move inner codes to Github
   - [x] add README and examples
   - [x] support pip install
   - [x] improvements

**Comment by Yancey0623** [comment]
Some supplement:
- An SQLFlow + XGBoost example on the notebook, I think it's an e2e example, maybe we can reuse the iris dataset.
- Can switch SQLFlow_submmiter in the notebook.

> [python] SqlflowModelSource
If only support local mode, we can use LocalModelSource instead.

I believe we only support local training in this milestone,  how about consider dist mode in the next milestone?

**Comment by sperlingxx** [comment]
@Yancey1989 @Echo9573 @typhoonzero @tonyyang-svail @BlackPoint-CX @weiguoz 
Since all tasks has been done. Can we close this TODO list?

**Comment by typhoonzero** [comment]
@sperlingxx Sure.
