### ISSUE TITLE
[TODO] Implement Analyze SQL in SQLFlow

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#707]
As the discussion in the morning, we are planning to support **EXPLAIN** in SQLFlow in a simple goal:
- Users can use **Analyze SQL** to explain the machine learning model, and show a figure in Jupyter.
- Use `shap` toolkit to explain the model.
- Verify the `ANALYZE SQL` on xgboost and TF model.

 TODO:
- [x] Design doc. @Yancey1989 #710 
- [x] Improve the lexer&parser to support `ANALYZE` keyword. @tonyyang-svail 
- [x] [Implement `ExplainFiller` struct in golang](https://github.com/sql-machine-learning/sqlflow/pull/751).
- [x] [Implement `shap_codegen` to generate the SHAP program](https://github.com/sql-machine-learning/sqlflow/pull/762/files).
- [x] Show the SHAP figure, an HTML file, in Jupyter. The SQLFlow server generates the figure and returns its HTML representation in a single message. @tonyyang-svail 
https://github.com/sql-machine-learning/sqlflow/blob/c2cceccef270a1c6faf9ccba5c8b3d3f91f870f0/server/proto/sqlflow.proto#L43
- [x] An example to show how to use `EXPLAIN` in Jupyter.

**Comment by tonyyang-svail** [comment]
> Show the SHAP figure, an HTML file, in Jupyter. The SQLFlow server generates the figure and returns its HTML representation in a single message.

I have verified that, after the merge of https://github.com/sql-machine-learning/pysqlflow/pull/82 and https://github.com/sql-machine-learning/sqlflow/pull/735, we can display the figure on the client-side.

![Screen Shot 2019-08-28 at 4 57 04 PM](https://user-images.githubusercontent.com/29932814/63900283-e84a7200-c9b4-11e9-8eab-4271c95f7f0f.png)
