### ISSUE TITLE
XGBoost on SQLFlow

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#749]
TODO:
~~- [ ] To support xgboost and ant-xgboost in SQLFlow #758~~
- [x] Design Doc: XGBoost on SQLFlow @Yancey1989  #753 
- [x] Implement `codegen_xgb` which can run e2e on the TRAIN SQL. @Yancey1989  #765 
- [x] Convert the WITH clause to `xgboost.train` arguments and XGBoost Parameters. @Yancey1989  #780 
- [x] Support `PREDICT` using the trained model. @typhoonzero 
- [x] Verify with `ANALYZE` SQL @Yancey1989 #790 
- [x] [enhancement] Verify parameters according the difference `booster` type, ref: https://xgboost.readthedocs.io/en/latest/parameter.html#xgboost-parameters
~~- [ ] [enhancement] Survey auto-train with XGBoost.~~
~~- [ ] Support sparse data format~~

**Comment by tonyyang-svail** [comment]
There are two training APIs. One is [`xgboost.train`](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.train) that returns a `Booster` object; One is Scikit Learn API like [`XGBRegressor.fit`](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBRegressor.fit) that belongs to a `xgboost.sklearn.XGBModel` object.

We choose the former because the latter is directly supported (need to call [`get_booster`](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBRegressor.get_booster)) by SHAP as described at https://github.com/sql-machine-learning/sqlflow/issues/727#issuecomment-525712427.

**Comment by Yancey0623** [comment]
Hi @tonyyang-svail ,thanks for your remind, would use the `xgboost.train` API.

**Comment by shendiaomo** [comment]
Can we close this issue now? @Yancey1989 @typhoonzero @tonyyang-svail

**Comment by Yancey0623** [comment]
@shendiaomo sure, thanks for reminding.
