### ISSUE TITLE
[TODO List] run Cluster Model in SQLFlow

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#768]
**Is your feature request related to a problem? Please describe.**
We prefer to implement  [Cluster Model Design Doc] in SQLFlow, the task list is as follows:

- [x] Implement ClusterModel which should be a [Model subclassing](https://keras.io/models/about-keras-models/#model-subclassing), and contribute to [SQLFlow Models](https://github.com/sql-machine-learning/models) repo. [models.PR: 16](https://github.com/sql-machine-learning/models/pull/16)
- [x] Refine TF codegen in SQLFlow to support custom `pre_train`, `train_loop` function. [PR: 838](https://github.com/sql-machine-learning/sqlflow/pull/838)
- [x] A tutorial to introduce how to run ClusterModel on SQLFlow

**Comment by tonyyang-svail** [comment]
The tutorial was submitted at https://github.com/sql-machine-learning/sqlflow/pull/927
