### ISSUE TITLE
[Intermediate Representation] Analysis codegen refactor TODO list

### ISSUE THREAD

**Issue by weiguoz** [sql-machine-learning/sqlflow#978]
As discussed in the [IR design doc](https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/design_intermediate_representation.md), we will generate the Python submitter program from the intermediate representation.

- [x] Generate the `AnalyzeIR` from SQL. #976 
- [x] Generate the analysis program. #975 
- [x] Switch to the new analysis which generated by IR. #977
